AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  STACK:
    Type: String
    Default: prod
  FIREHOSE:
    Type: String
    Default: FIREHOSE PLACEHOLDER
Resources:
  FeedbackSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Join:
        - '-'
        - - SLUBot-Feedback
          - Ref: STACK
      TopicName:
        Fn::Join:
        - '-'
        - - SLUBot-Feedback
          - Ref: STACK
  slubusstops:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join:
        - '-'
        - - slu-bus-stops
          - Ref: STACK
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  slubusroutes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join:
        - '-'
        - - slu-bus-routes
          - Ref: STACK
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  slubuses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Join:
        - '-'
        - - slu-buses
          - Ref: STACK
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  qnawhatsopennow:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - qna-opennow
          - Ref: STACK
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://sluhookdev/a5098a00d10d43a508e08f776de65922
      Description: returns what restaurants/dining halls are open at SLU
      MemorySize: 2432
      Timeout: 63
      Environment:
        Variables:
          PATH: /var/task/bin
          PYTHONPATH: /var/task/lib
  qnabushandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - qna-bus-handler
          - Ref: STACK
      Handler: lambda_function.bushandler
      Runtime: python3.6
      CodeUri: s3://sluhookdev/c970944ff75fa10fc0587d508fda9e1f
      Description: returns bus information for SLU routes
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUSES:
            Ref: slubuses
          ROUTES:
            Ref: slubusroutes
          STOPS:
            Ref: slubusstops
          Intro: The following bus schedules were found
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          Resource:
          - Fn::GetAtt:
            - slubusroutes
            - Arn
          - Fn::GetAtt:
            - slubuses
            - Arn
          - Fn::GetAtt:
            - slubusstops
            - Arn
  ThumbsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - qna-feedback
          - Ref: STACK
      Handler: lambda_function.feedback_handler
      Runtime: python3.6
      Environment:
        Variables:
          FIREHOSE_NAME:
            Ref: FIREHOSE
          SNS_TOPIC_ARN:
            Ref: FeedbackSNS
      CodeUri: s3://sluhookdev/3d6e78996455221880d08d1ecca5d46c
      Description: enables thumbs down and thumbs up feedback backend
      MemorySize: 128
      Timeout: 10
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - firehose:PutRecordBatch
          - firehose:PutRecord
          Resource: '*'
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - sns:Publish
          Resource:
            Ref: FeedbackSNS
  slupopulateBusData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - qna-populate-busdata
          - Ref: STACK
      Handler: lambda_function.populateData
      Runtime: python3.6
      CodeUri: s3://sluhookdev/2d751b4ceca68dcdbd44cd4a36e37c6e
      Description: Poplulates doublemap data to dynamodb table
      MemorySize: 128
      Timeout: 10
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: dynamodb:*
          Resource:
          - Fn::GetAtt:
            - slubusroutes
            - Arn
          - Fn::GetAtt:
            - slubuses
            - Arn
          - Fn::GetAtt:
            - slubusstops
            - Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule:
              Fn::Sub: rate(3 hours)
      Environment:
        Variables:
          BUSES:
            Ref: slubuses
          ROUTES:
            Ref: slubusroutes
          STOPS:
            Ref: slubusstops
  qnasodexohandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Join:
        - '-'
        - - qna-sodexo-handler
          - Ref: STACK
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://sluhookdev/399414e5f37db01feb64b4da1f56db5e
      Description: returns information for grand dining hall menu items such as vegan
        options and allergen arguments
      MemorySize: 256
      Timeout: 30
Outputs:
  PopulateBus:
    Description: Arn for populate bus data lambda hook
    Value:
      Fn::GetAtt:
      - slupopulateBusData
      - Arn
  ThumbsFunction:
    Description: Arn for populate bus data lambda hook
    Value:
      Fn::GetAtt:
      - ThumbsFunction
      - Arn
  BusHandler:
    Description: Arn for populate bus data lambda hook
    Value:
      Fn::GetAtt:
      - qnabushandler
      - Arn
  OpenNow:
    Description: Arn for populate bus data lambda hook
    Value:
      Fn::GetAtt:
      - qnawhatsopennow
      - Arn
  SodexoHandler:
    Description: Arn for sodexo handler
    Value:
      Fn::GetAtt:
      - qnasodexohandler
      - Arn
