AWSTemplateFormatVersion: '2010-09-09' 
Transform: AWS::Serverless-2016-10-31 


Parameters:

  STACK:
      Type: String
      Default: prod

  FIREHOSE:
      Type: String
      Default: FIREHOSE PLACEHOLDER
      
Resources:
  FeedbackSNS:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: !Join
                      - '-'
                      - - 'SLUBot-Feedback'
                        - !Ref STACK

      TopicName: !Join
                      - '-'
                      - - 'SLUBot-Feedback'
                        - !Ref STACK

  slubusstops:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
                      - '-'
                      - - 'slu-bus-stops'
                        - !Ref STACK
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  slubusroutes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
                      - '-'
                      - - 'slu-bus-routes'
                        - !Ref STACK
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
  slubuses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join
                      - '-'
                      - - 'slu-buses'
                        - !Ref STACK
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  qnawhatsopennow:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join
                      - '-'
                      - - 'qna-opennow'
                        - !Ref STACK
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: lambda_hooks/qna_whats_open_now/
      Description: 'returns what restaurants/dining halls are open at SLU'
      MemorySize: 2432
      Timeout: 63
      Environment:
        Variables:
          PATH: /var/task/bin
          PYTHONPATH: /var/task/lib

  qnabushandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join
                      - '-'
                      - - 'qna-bus-handler'
                        - !Ref STACK
      Handler: lambda_function.bushandler
      Runtime: python3.6
      CodeUri: lambda_hooks/qna_bus_handler
      Description: 'returns bus information for SLU routes'
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUSES: !Ref slubuses
          ROUTES: !Ref slubusroutes
          STOPS: !Ref slubusstops
          Intro: The following bus schedules were found
      Policies: 
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                -  dynamodb:Scan
                -  dynamodb:Query
                -  dynamodb:BatchGetItem
                -  dynamodb:DescribeTable
              Resource:
                - !GetAtt slubusroutes.Arn
                - !GetAtt slubuses.Arn
                - !GetAtt slubusstops.Arn

  ThumbsFunction: 
    Type: AWS::Serverless::Function 
    Properties: 
      FunctionName: !Join
                      - '-'
                      - - 'qna-feedback'
                        - !Ref STACK
      Handler: lambda_function.feedback_handler
      Runtime: python3.6
      Environment:
        Variables:
          FIREHOSE_NAME: !Ref FIREHOSE
          SNS_TOPIC_ARN: !Ref FeedbackSNS
      CodeUri: lambda_hooks/thumbs_function/
      Description: enables thumbs down and thumbs up feedback backend
      MemorySize: 128 
      Timeout: 10 
      #Role: arn:aws:iam::252158453973:role/QnABot-FulfillmentLambdaRole-15HCCZ2BJOCRJ  
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
           - Effect: Allow
             Action:
              - firehose:PutRecordBatch
              - firehose:PutRecord
             Resource: '*'
        - Version: '2012-10-17' # Policy Document
          Statement:
           - Effect: Allow
             Action: 
              - sns:Publish
             Resource: !Ref FeedbackSNS

  slupopulateBusData:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join
                      - '-'
                      - - 'qna-populate-busdata'
                        - !Ref STACK
      Handler: lambda_function.populateData
      Runtime: python3.6
      CodeUri: lambda_hooks/slu_populate_bus_data/
      Description: 'Poplulates doublemap data to dynamodb table'
      MemorySize: 128
      Timeout: 10
      Policies: 
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource:
                - !GetAtt slubusroutes.Arn
                - !GetAtt slubuses.Arn
                - !GetAtt slubusstops.Arn
      Events:
          ScheduledEvent:
              Type: Schedule
              Properties:
                  Schedule: !Sub "rate(3 hours)"
      Environment:
        Variables:
          BUSES: !Ref slubuses
          ROUTES: !Ref slubusroutes
          STOPS: !Ref slubusstops

  qnasodexohandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Join
                      - '-'
                      - - 'qna-sodexo-handler'
                        - !Ref STACK
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: lambda_hooks/qna_sodexo_handler
      Description: 'returns information for grand dining hall menu items such as vegan options and allergen arguments'
      MemorySize: 256
      Timeout: 30

Outputs:

  PopulateBus:
    Description: "Arn for populate bus data lambda hook"
    Value: !GetAtt slupopulateBusData.Arn

  ThumbsFunction:
    Description: "Arn for populate bus data lambda hook"
    Value: !GetAtt ThumbsFunction.Arn

  BusHandler:
    Description: "Arn for populate bus data lambda hook"
    Value: !GetAtt qnabushandler.Arn

  OpenNow:
    Description: "Arn for populate bus data lambda hook"
    Value: !GetAtt qnawhatsopennow.Arn
    
  SodexoHandler:
    Description: "Arn for sodexo handler"
    Value: !GetAtt qnasodexohandler.Arn